export enum EntityType {
    RequestEntry = 1,
    Request = 2,
    Group = 3,
    Body = 4,
    Headers = 5,
    Scenario = 6,
    Authorization = 7,
    Certificate = 8,
    Proxy = 9,
    Data = 10,
    Parameters = 11,
    Defaults = 12,
    Warnings = 13,
}